export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_ALL_PLAYERS_ERROR = 'GET_ALL_PLAYERS_ERROR';

export const GET_GUESSED_PLAYER = 'GET_GUESSED_PLAYER';
export const GET_GUESSED_PLAYER_ERROR = 'GET_GUESSED_PLAYER_ERROR';

export const GET_ALL_PLAYER_NAMES = 'GET_ALL_PLAYER_NAMES';
export const GET_ALL_PLAYER_NAMES_ERROR = 'GET_ALL_PLAYER_NAMES_ERROR';

export const SELECT_RANDOM_NUMBER = 'SELECT_RANDOM_NUMBER';